### PR TITLE
Update to pr13

### LINKED ISSUE #7: Design Suggestion
please do the module again for the dark theme of Bootsrap4 (the old default theme) a light theme isnt very good.

### PR DESCRIPTION
**Pull request by PadowYT2**
* Deprecated -> new
* Formatting
* i18n

Closes #7 (old), closes #14, closes #15 (due to i18n)

Also, dm Derkades about [translate.namelessmc.com](https://translate.namelessmc.com)
https://cdn.padow.ru/VmWp

### CODE REVIEW

**Review by iAbdullahHassan — APPROVED** [review]

**Comment by Justman10000** [comment]
What?

**Comment by Justman10000** [comment]
You can still merge existing PRs? lol? Stop just destroying other people's work!

**Comment by PadowYT2** [comment]
what

**Comment by Justman10000** [comment]
I mean @Xemah

**Comment by iAbdullahHassan** [comment]
@Justman10000 Wdym?

**Pull request merged**
